Packaging cleanups
rvandegrift/efl pull request #1
Opened 2016-11-04 16:42 UTC by nbraud

This makes the package Lintian-clean,
and updates the maintainership metadata.

Please wait for the upload to reach experimental before merging.

2016-11-04 21:33 UTC, rvandegrift requested changes

2016-11-04 21:33 UTC, rvandegrift commented on debian/control
> +Build-Depends-Indep: doxygen, ghostscript, imagemagick, texlive-font-utils
efl-docs only ships the html documentation.  Is this required to generate it?

2016-11-04 21:33 UTC, rvandegrift commented on debian/changelog
> +
Could you regenerate without debian/changelog?  gbp dch will generate it automatically at release to avoid merge conflicts along the way

2016-11-25 22:24 UTC, nbraud commented on debian/control
> +Build-Depends-Indep: doxygen, ghostscript, imagemagick, texlive-font-utils
@rvandegrift I definitely had a build failure without those.
You can test yourself by running the build in a clean environment (either with sbuild or pbuilder)

2016-11-25 22:24 UTC, nbraud commented on debian/changelog
> +
Sure

2016-11-25 22:27 UTC, nbraud commented on debian/changelog
> +
PS: The changelog was in a separate commit, so you could have dropped that yourself anyhow.

2016-11-27 22:20 UTC, merged